//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBS_IT_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public int Id_Service { get; set; }
        public int Id_Client { get; set; }
        public int Id_Staff { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Status { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual ServicesSet ServicesSet { get; set; }
        public virtual StaffSet StaffSet { get; set; }
    }
}
